For evaluating the solution of big matrix, it is more practical to use the iterative methods due to the limitation of computational efforts and storage.

# Pure Iteration

## Definition
- Linear system $Ax = b$.
- Residual $r_k = Ax - Ax_k = b - Ax_k$.
- Preconditioner $P \approx A$.
- Splitting $Px = (P-A)x+b$.
- Iteration $Px_{k+1} = (P-A)x_k + b$.

Two conditions on $P$ make the iteration successful:
1. The new $x_{k+1}$ must be quickly computable, in other words, $x_{k+1}$ in the iteration equation must be fast to solve.
2. The error $e_k = x-x_k$ should approach zero as rapidly as possible.

## Convergence
- Iteration Error $Pe_{k+1} = (P-A)e_k$.
- Error $e_{k+1} = (I-P^{-1}A)e_k = Me_k$.

Every eigenvalue of $M = I-P^{-1}A$ must have $|\lambda(M)|<1$ to keep the error convergence. And the magnitude of the biggest eigenvalue determines the convergence rate of the method.

### Jacobi
$$P = \text{diagonal part } D \text{ of } A$$

### Weighted Jacobi
$$P = \frac{1}{w}\cdot \text{diagonal part } D \text{ of } A\qquad w\in(0,1)$$

### Gauss-Seidel
$$P = \text{lower triangular part of }A$$

### Overrelaxation (SOR)
$$P = \text{diagonal part} D + w\cdot\text{lower triangular part of }A$$

### Incomplete LU
$$P = (\text{approximation to }L)(\text{approximation to } U)$$


In [9]:
import numpy as np
from scipy.sparse import csc_matrix, linalg

A = np.array([[ 2, -1,  0,  0],
              [-1,  2, -1,  0],
              [ 0, -1,  2, -1],
              [ 0,  0, -1,  2]])

b = np.random.uniform(-10, 10, 4)

def Jacobi():
    x = np.array([0, 0, 0, 0])
    I = np.identity(len(x))
    #P = A * np.identity(len(x))
    #invP = np.linalg.inv(P)
    invP = 1/2
    M = I - invP * A
    #print(np.linalg.eig(M))
    for i in range(16):
        x = M @ x + invP * b
    return x

def Weighted_Jacobi():
    w = 2/3
    x = np.array([0, 0, 0, 0])
    I = np.identity(len(x))
    #P = A * np.identity(len(x))/w
    #invP = np.linalg.inv(P)
    invP = w/2
    M = I - invP * A
    #print(np.linalg.eig(M))
    for i in range(16):
        x = M @ x + invP * b
    return x

def Gauss_seidel():
    x = np.array([0, 0, 0, 0])
    I = np.identity(len(x))
    P = np.tril(A, 0)
    invP = np.linalg.inv(P)
    M = I - invP @ A
    #print(np.linalg.eig(M))
    for i in range(16):
        x = M @ x + invP @ b
    return x

# def ILU():
#     x = np.array([0, 0, 0, 0])
#     I = np.identity(len(x))
#     lu = linalg.spilu(csc_matrix(A))
#     P = (lu.L * lu.U).A
#     print(P)
#     invP = np.linalg.inv(P)
#     M = I - invP @ A
#     print(np.linalg.eig(M))
#     for i in range(16):
#         x = M @ x + invP @ b
#     return x

def main():
    x = np.linalg.solve(A, b)
    print("x is \n", x)
    x = Jacobi()
    print("Jacobi approximation x is \n", x)
    x = Weighted_Jacobi()
    print("Weighted Jacobi approximation x is \n", x)
    x = Gauss_seidel()
    print("Gauss-seidel approximation x is \n", x)
#     x = ILU()
#     print("ILU approximation x is \n", x)

if __name__=="__main__":
    main()

x is 
 [6.20274963 6.45249155 5.62538114 4.55284269]
Jacobi approximation x is 
 [6.06029466 6.22668765 5.3948842  4.4132882 ]
Weighted Jacobi approximation x is 
 [5.7289306  5.68587636 4.8588155  4.07910384]
Gauss-seidel approximation x is 
 [6.19581532 6.44341443 5.6180376  4.54917092]
